from p0707_solution import Solution


class TestClass:

    s = Solution()

    def run_funcs(self, args, expected):
        """Run test case for each implementation in Solution"""
        for implementation in self.s.implementations:
            func = getattr(self.s, implementation)
            result = func(*args)
            assert result == expected

    def test1_example1(self):
        args = [
            [
                "MyLinkedList",
                "addAtHead",
                "addAtTail",
                "addAtIndex",
                "get",
                "deleteAtIndex",
                "get",
            ],
            [[], [1], [3], [1, 2], [1], [1], [1]],
        ]
        expected = [None, None, None, None, 2, None, 3]
        self.run_funcs(args, expected)

    def test2_example2(self):
        args = [
            [
                "MyLinkedList",
                "get",
                "deleteAtIndex",
                "deleteAtIndex",
                "addAtIndex",
                "addAtIndex",
                "addAtHead",
                "addAtIndex",
            ],
            [[], [1], [0], [1], [2, 1], [0, 0], [1], [3, 3]],
        ]
        expected = [None, -1, None, None, None, None, None, None]
        self.run_funcs(args, expected)

    def test3_more_complex(self):
        args = [
            [
                "MyLinkedList",
                "addAtHead",
                "addAtHead",
                "addAtHead",
                "addAtIndex",
                "deleteAtIndex",
                "addAtHead",
                "addAtTail",
                "get",
                "addAtHead",
                "addAtIndex",
                "addAtHead",
            ],
            [[], [7], [2], [1], [3, 0], [2], [6], [4], [4], [4], [5, 0], [6]],
        ]
        expected = [
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            4,
            None,
            None,
            None,
        ]
        self.run_funcs(args, expected)

    def test4_most_complex(self):
        args = [
            [
                "MyLinkedList",
                "addAtHead",
                "addAtTail",
                "addAtTail",
                "get",
                "get",
                "addAtTail",
                "addAtIndex",
                "addAtHead",
                "addAtHead",
                "addAtTail",
                "addAtTail",
                "addAtTail",
                "addAtTail",
                "get",
                "addAtHead",
                "addAtHead",
                "addAtIndex",
                "addAtIndex",
                "addAtHead",
                "addAtTail",
                "deleteAtIndex",
                "addAtHead",
                "addAtHead",
                "addAtIndex",
                "addAtTail",
                "get",
                "addAtIndex",
                "addAtTail",
                "addAtHead",
                "addAtHead",
                "addAtIndex",
                "addAtTail",
                "addAtHead",
                "addAtHead",
                "get",
                "deleteAtIndex",
                "addAtTail",
                "addAtTail",
                "addAtHead",
                "addAtTail",
                "get",
                "deleteAtIndex",
                "addAtTail",
                "addAtHead",
                "addAtTail",
                "deleteAtIndex",
                "addAtTail",
                "deleteAtIndex",
                "addAtIndex",
                "deleteAtIndex",
                "addAtTail",
                "addAtHead",
                "addAtIndex",
                "addAtHead",
                "addAtHead",
                "get",
                "addAtHead",
                "get",
                "addAtHead",
                "deleteAtIndex",
                "get",
                "addAtHead",
                "addAtTail",
                "get",
                "addAtHead",
                "get",
                "addAtTail",
                "get",
                "addAtTail",
                "addAtHead",
                "addAtIndex",
                "addAtIndex",
                "addAtHead",
                "addAtHead",
                "deleteAtIndex",
                "get",
                "addAtHead",
                "addAtIndex",
                "addAtTail",
                "get",
                "addAtIndex",
                "get",
                "addAtIndex",
                "get",
                "addAtIndex",
                "addAtIndex",
                "addAtHead",
                "addAtHead",
                "addAtTail",
                "addAtIndex",
                "get",
                "addAtHead",
                "addAtTail",
                "addAtTail",
                "addAtHead",
                "get",
                "addAtTail",
                "addAtHead",
                "addAtTail",
                "get",
                "addAtIndex",
            ],
            [
                [],
                [84],
                [2],
                [39],
                [3],
                [1],
                [42],
                [1, 80],
                [14],
                [1],
                [53],
                [98],
                [19],
                [12],
                [2],
                [16],
                [33],
                [4, 17],
                [6, 8],
                [37],
                [43],
                [11],
                [80],
                [31],
                [13, 23],
                [17],
                [4],
                [10, 0],
                [21],
                [73],
                [22],
                [24, 37],
                [14],
                [97],
                [8],
                [6],
                [17],
                [50],
                [28],
                [76],
                [79],
                [18],
                [30],
                [5],
                [9],
                [83],
                [3],
                [40],
                [26],
                [20, 90],
                [30],
                [40],
                [56],
                [15, 23],
                [51],
                [21],
                [26],
                [83],
                [30],
                [12],
                [8],
                [4],
                [20],
                [45],
                [10],
                [56],
                [18],
                [33],
                [2],
                [70],
                [57],
                [31, 24],
                [16, 92],
                [40],
                [23],
                [26],
                [1],
                [92],
                [3, 78],
                [42],
                [18],
                [39, 9],
                [13],
                [33, 17],
                [51],
                [18, 95],
                [18, 33],
                [80],
                [21],
                [7],
                [17, 46],
                [33],
                [60],
                [26],
                [4],
                [9],
                [45],
                [38],
                [95],
                [78],
                [54],
                [42, 86],
            ],
        ]
        expected = [
            None,
            None,
            None,
            None,
            -1,
            2,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            84,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            16,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            37,
            None,
            None,
            None,
            None,
            None,
            23,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            19,
            None,
            17,
            None,
            None,
            56,
            None,
            None,
            31,
            None,
            17,
            None,
            12,
            None,
            None,
            None,
            None,
            None,
            None,
            None,
            40,
            None,
            None,
            None,
            37,
            None,
            76,
            None,
            42,
            None,
            None,
            None,
            None,
            None,
            None,
            80,
            None,
            None,
            None,
            None,
            43,
            None,
            None,
            None,
            40,
            None,
        ]
        self.run_funcs(args, expected)
